export interface Community {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  members: number;
  posts: number;
  category: string;
  isJoined: boolean;
  admins: string[];
  tags: string[];
  isVerified: boolean;
  createdDate: string;
}

export const COMMUNITY_MEMBERS: Record<string, Array<{ userId: string; kp: number }>> = {
  c1: [
    { userId: 'u4', kp: 1567 },
    { userId: 'u2', kp: 1243 },
    { userId: 'u1', kp: 847 },
    { userId: 'u5', kp: 734 },
    { userId: 'u3', kp: 312 },
  ],
  c2: [
    { userId: 'u2', kp: 1243 },
    { userId: 'u4', kp: 892 },
    { userId: 'u6', kp: 456 },
    { userId: 'u1', kp: 389 },
    { userId: 'u7', kp: 234 },
  ],
  c3: [
    { userId: 'u1', kp: 847 },
    { userId: 'u5', kp: 734 },
    { userId: 'u3', kp: 512 },
    { userId: 'u2', kp: 298 },
    { userId: 'u4', kp: 187 },
  ],
  c9: [
    { userId: 'u3', kp: 967 },
    { userId: 'u5', kp: 734 },
    { userId: 'u1', kp: 523 },
    { userId: 'u4', kp: 412 },
    { userId: 'u2', kp: 356 },
  ],
};

export const COMMUNITIES: Community[] = [
  {
    id: 'c1',
    name: 'IKS Enthusiasts',
    description: 'Exploring Indian Knowledge Systems — from Vedic mathematics to Ayurveda, astronomy to art.',
    icon: '☸',
    color: '#2d91ab',
    members: 2847,
    posts: 1456,
    category: 'Education',
    isJoined: true,
    admins: ['u4', 'u2'],
    tags: ['IKS', 'Vedic', 'Sanskrit', 'Philosophy'],
    isVerified: true,
    createdDate: '2023-12-01',
  },
  {
    id: 'c2',
    name: 'Ayurveda Practitioners',
    description: 'Community for Ayurveda doctors, researchers, and enthusiasts. Sharing knowledge, research, and healing.',
    icon: '🌿',
    color: '#4caf50',
    members: 1923,
    posts: 934,
    category: 'Health & Well Being',
    isJoined: true,
    admins: ['u2'],
    tags: ['Ayurveda', 'Health', 'Healing', 'Herbs'],
    isVerified: true,
    createdDate: '2023-12-15',
  },
  {
    id: 'c3',
    name: 'Dharmic Developers',
    description: 'Builders creating technology solutions aligned with Dharmic values and Indian culture.',
    icon: '⚡',
    color: '#ff8f0e',
    members: 1456,
    posts: 789,
    category: 'Technology',
    isJoined: true,
    admins: ['u1'],
    tags: ['Technology', 'OpenSource', 'AI', 'IndianTech'],
    isVerified: true,
    createdDate: '2024-01-01',
  },
  {
    id: 'c4',
    name: 'IITD Alumni Network',
    description: 'IIT Delhi community — collaborating to solve India\'s toughest problems through innovation.',
    icon: '🎓',
    color: '#9c27b0',
    members: 3201,
    posts: 2103,
    category: 'Education',
    isJoined: false,
    admins: ['u5'],
    tags: ['IITD', 'Research', 'Innovation', 'Alumni'],
    isVerified: true,
    createdDate: '2023-11-15',
  },
  {
    id: 'c5',
    name: 'Dharmic Teachers',
    description: 'Acharyas and Gurus sharing wisdom, connecting with seekers across traditions.',
    icon: '🪔',
    color: '#f44336',
    members: 876,
    posts: 1234,
    category: 'Spirituality',
    isJoined: false,
    admins: ['u4', 'u2'],
    tags: ['Teaching', 'Dharma', 'Spirituality', 'Meditation'],
    isVerified: true,
    createdDate: '2023-12-20',
  },
  {
    id: 'c6',
    name: 'Dharmic Investors',
    description: 'Patient capital for ideas and ventures rooted in Dharmic principles and Indian values.',
    icon: '💎',
    color: '#607d8b',
    members: 654,
    posts: 432,
    category: 'Finance',
    isJoined: false,
    admins: ['u3'],
    tags: ['Investment', 'Finance', 'Startup', 'Dharma'],
    isVerified: true,
    createdDate: '2024-01-10',
  },
  {
    id: 'c7',
    name: 'Dharmic Artists',
    description: 'Visual artists, musicians, writers and performers preserving and reimagining Indian art forms.',
    icon: '🎨',
    color: '#e91e63',
    members: 1123,
    posts: 876,
    category: 'Art & Culture',
    isJoined: false,
    admins: ['u6'],
    tags: ['Art', 'Music', 'Culture', 'Creativity'],
    isVerified: true,
    createdDate: '2024-01-05',
  },
  {
    id: 'c8',
    name: 'Climate Scientists',
    description: 'Researchers and activists addressing climate crisis through indigenous wisdom and modern science.',
    icon: '🌍',
    color: '#009688',
    members: 789,
    posts: 567,
    category: 'Science',
    isJoined: false,
    admins: ['u5'],
    tags: ['Climate', 'Environment', 'Research', 'Science'],
    isVerified: false,
    createdDate: '2024-02-01',
  },
  {
    id: 'c9',
    name: 'Social Entrepreneurs',
    description: 'Impact-driven founders building ventures that solve real problems in Bharat.',
    icon: '🚀',
    color: '#ff5722',
    members: 1345,
    posts: 678,
    category: 'Business',
    isJoined: true,
    admins: ['u3', 'u5'],
    tags: ['Entrepreneurship', 'Impact', 'Social', 'Innovation'],
    isVerified: true,
    createdDate: '2024-01-15',
  },
  {
    id: 'c10',
    name: 'BioScience Research',
    description: 'Biologists and medical researchers collaborating on breakthrough discoveries.',
    icon: '🔬',
    color: '#3f51b5',
    members: 567,
    posts: 345,
    category: 'Science',
    isJoined: false,
    admins: ['u5'],
    tags: ['Biology', 'Medicine', 'Research', 'Science'],
    isVerified: false,
    createdDate: '2024-02-15',
  },
  {
    id: 'c11',
    name: 'Dharmic Lawyers',
    description: 'Legal professionals championing justice aligned with Dharmic values and constitutional rights.',
    icon: '⚖️',
    color: '#795548',
    members: 432,
    posts: 234,
    category: 'Law',
    isJoined: false,
    admins: ['u7'],
    tags: ['Law', 'Justice', 'Rights', 'Dharma'],
    isVerified: false,
    createdDate: '2024-03-01',
  },
];
