export type PostType = 'text' | 'audio' | 'image' | 'video' | 'product';
export type Reaction = 'truth' | 'insight' | 'dharmic';

export interface Post {
  id: string;
  authorId: string;
  authorName: string;
  authorUsername: string;
  authorAvatar: string;
  authorKarma: number;
  type: PostType;
  title?: string;
  content: string;
  imageUrl?: string;
  audioUrl?: string;
  community?: string;
  communityId?: string;
  tags: string[];
  reactions: {
    truth: number;
    insight: number;
    dharmic: number;
  };
  comments: number;
  shares: number;
  bookmarks: number;
  timestamp: string;
  isPinned?: boolean;
  isBookmarked?: boolean;
}

export const POSTS: Post[] = [
  {
    id: 'p1',
    authorId: 'u4',
    authorName: 'Ananya Krishnan',
    authorUsername: 'ananya.krishnan',
    authorAvatar: '',
    authorKarma: 1567,
    type: 'text',
    title: 'Vedic Mathematics: A Modern Renaissance',
    content: 'The Vedic sutras offer extraordinary computational shortcuts that were documented thousands of years ago. Today, as we build AI systems, I find myself returning to these ancient algorithms for inspiration. The principle of "Anurupyena" (proportionality) maps beautifully to modern neural network optimization. We are not reinventing — we are remembering.',
    community: 'IKS Enthusiasts',
    communityId: 'c1',
    tags: ['VedicMath', 'IKS', 'AI', 'AncientWisdom'],
    reactions: { truth: 234, insight: 189, dharmic: 156 },
    comments: 47,
    shares: 89,
    bookmarks: 123,
    timestamp: '2024-04-01T09:30:00Z',
    isPinned: true,
    isBookmarked: false,
  },
  {
    id: 'p2',
    authorId: 'u2',
    authorName: 'Dr. Priya Nair',
    authorUsername: 'priya.nair',
    authorAvatar: '',
    authorKarma: 1243,
    type: 'audio',
    title: 'Podcast: Tridosha Theory and Modern Genomics',
    content: 'In this 45-minute deep dive, I explore the surprising correlations between Ayurvedic Tridosha theory and modern epigenetic research. The Vata-Pitta-Kapha framework may actually map to distinct metabolic and neurological phenotypes that modern science is only beginning to understand.',
    community: 'Ayurveda Practitioners',
    communityId: 'c2',
    tags: ['Ayurveda', 'Genomics', 'Research', 'Tridosha'],
    reactions: { truth: 178, insight: 234, dharmic: 145 },
    comments: 32,
    shares: 67,
    bookmarks: 98,
    timestamp: '2024-04-01T08:00:00Z',
    isBookmarked: true,
  },
  {
    id: 'p3',
    authorId: 'u1',
    authorName: 'Arjun Sharma',
    authorUsername: 'arjun.sharma',
    authorAvatar: '',
    authorKarma: 847,
    type: 'text',
    title: 'Building Dharmic Network: Open Source Philosophy',
    content: 'Just open-sourced the core protocol layer of our decentralized identity system. Inspired by the Vasudhaiva Kutumbakam principle — the world is one family — we are building infrastructure that respects data sovereignty. Every user owns their identity, their content, and their connections. No corporation in the middle.',
    community: 'Dharmic Developers',
    communityId: 'c3',
    tags: ['OpenSource', 'Blockchain', 'Identity', 'Dharma'],
    reactions: { truth: 145, insight: 167, dharmic: 201 },
    comments: 28,
    shares: 54,
    bookmarks: 67,
    timestamp: '2024-03-31T18:45:00Z',
    isBookmarked: false,
  },
  {
    id: 'p4',
    authorId: 'u5',
    authorName: 'Rahul Gupta',
    authorUsername: 'rahul.gupta',
    authorAvatar: '',
    authorKarma: 734,
    type: 'image',
    title: 'Delhi Air Quality: Community Action Plan',
    content: 'Our IITD team has mapped 847 pollution hotspots across Delhi using a community-deployed IoT sensor network. The data reveals that 73% of PM2.5 comes from just 12 industrial clusters. We have a targeted intervention plan ready. Looking for dharmic investors and policy advocates to move this forward.',
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format',
    community: 'Climate Scientists',
    communityId: 'c8',
    tags: ['Climate', 'Delhi', 'AirQuality', 'Research'],
    reactions: { truth: 312, insight: 256, dharmic: 189 },
    comments: 63,
    shares: 134,
    bookmarks: 201,
    timestamp: '2024-03-31T14:20:00Z',
    isBookmarked: false,
  },
  {
    id: 'p5',
    authorId: 'u6',
    authorName: 'Meera Devi',
    authorUsername: 'meera.devi',
    authorAvatar: '',
    authorKarma: 856,
    type: 'image',
    title: 'Warli Art Meets Digital Canvas',
    content: 'This series explores Warli tribal art patterns through generative AI. Each piece starts with traditional geometric motifs — circles, triangles, dots — and expands into digital mandalas that pulse with ancient symbolism. Available as limited digital prints. Proceeds support tribal artisans in Maharashtra.',
    imageUrl: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&auto=format',
    community: 'Dharmic Artists',
    communityId: 'c7',
    tags: ['Art', 'Warli', 'DigitalArt', 'Tribal'],
    reactions: { truth: 189, insight: 134, dharmic: 267 },
    comments: 41,
    shares: 78,
    bookmarks: 145,
    timestamp: '2024-03-30T11:00:00Z',
    isBookmarked: true,
  },
  {
    id: 'p6',
    authorId: 'u3',
    authorName: 'Vikram Patel',
    authorUsername: 'vikram.patel',
    authorAvatar: '',
    authorKarma: 967,
    type: 'text',
    title: 'Dharmic Capital: Beyond Returns',
    content: 'Announcing our ₹50 Crore fund for ventures that create measurable social impact while maintaining financial sustainability. We are not a charity, but we measure success differently. Dharma first, Artha follows. Looking for founders building in health, education, environment, and culture sectors.',
    community: 'Dharmic Investors',
    communityId: 'c6',
    tags: ['Investment', 'Impact', 'Fund', 'StartupIndia'],
    reactions: { truth: 256, insight: 178, dharmic: 234 },
    comments: 89,
    shares: 167,
    bookmarks: 234,
    timestamp: '2024-03-29T16:30:00Z',
    isBookmarked: false,
  },
];

export const COMMUNITIES_POSTS: Post[] = [
  {
    id: 'cp1',
    authorId: 'u4',
    authorName: 'Ananya Krishnan',
    authorUsername: 'ananya.krishnan',
    authorAvatar: '',
    authorKarma: 1567,
    type: 'text',
    title: 'Sanskrit Grammar & Modern Linguistics: A Deep Dive',
    content: 'Pāṇini\'s Ashtadhyayi — written around 4th century BCE — contains 3,959 sutras that describe Sanskrit grammar with such precision that modern computational linguists are still studying it. The system is essentially a context-free grammar, anticipating formal language theory by 2,300 years. This is not mythology. This is history.',
    community: 'IKS Enthusiasts',
    communityId: 'c1',
    tags: ['Sanskrit', 'Linguistics', 'Panini', 'IKS'],
    reactions: { truth: 198, insight: 312, dharmic: 134 },
    comments: 56,
    shares: 78,
    bookmarks: 112,
    timestamp: '2024-04-02T07:15:00Z',
  },
  {
    id: 'cp2',
    authorId: 'u2',
    authorName: 'Dr. Priya Nair',
    authorUsername: 'priya.nair',
    authorAvatar: '',
    authorKarma: 1243,
    type: 'text',
    title: 'Seasonal Eating: What Your Grandparents Knew',
    content: 'Ritucharya — the Ayurvedic science of seasonal routines — prescribes specific foods, activities, and behaviors for each of the six seasons (Ritus). Summer demands cooling foods like amla, coriander, and coconut water. Winter calls for warming foods and oil massages. This isn\'t superstition; it\'s systems biology applied millennia ago.',
    community: 'Ayurveda Practitioners',
    communityId: 'c2',
    tags: ['Ayurveda', 'Ritucharya', 'Wellness', 'SeasonalEating'],
    reactions: { truth: 267, insight: 189, dharmic: 156 },
    comments: 44,
    shares: 91,
    bookmarks: 178,
    timestamp: '2024-04-02T06:00:00Z',
  },
  {
    id: 'cp3',
    authorId: 'u1',
    authorName: 'Arjun Sharma',
    authorUsername: 'arjun.sharma',
    authorAvatar: '',
    authorKarma: 847,
    type: 'text',
    title: 'Why Bharat Needs a Homegrown AI Stack',
    content: 'Our data is being used to train LLMs that don\'t understand our languages, our context, or our values. We need Indic-native models trained on Sanskrit, Tamil, Telugu, Kannada, and other classical texts. The Mahabharata alone has 1.8 million words — 10x the Iliad and Odyssey combined. Our training corpus is extraordinary. Our infrastructure investment is not.',
    community: 'Dharmic Developers',
    communityId: 'c3',
    tags: ['AI', 'Indic', 'Sanskrit', 'Technology', 'Bharat'],
    reactions: { truth: 389, insight: 267, dharmic: 312 },
    comments: 87,
    shares: 145,
    bookmarks: 234,
    timestamp: '2024-04-01T20:00:00Z',
  },
  {
    id: 'cp4',
    authorId: 'u7',
    authorName: 'Kiran Rao',
    authorUsername: 'kiran.rao',
    authorAvatar: '',
    authorKarma: 1089,
    type: 'text',
    title: 'Yoga Sutras as a Framework for Product Design',
    content: 'Patanjali\'s eight-limbed path (Ashtanga) maps beautifully to ethical product design. Ahimsa (non-harm) → data privacy. Satya (truth) → transparent algorithms. Aparigraha (non-greed) → sustainable business models. Dharana (concentration) → focused UX. The ancient frameworks still hold when applied thoughtfully.',
    community: 'IKS Enthusiasts',
    communityId: 'c1',
    tags: ['Yoga', 'Design', 'ProductDesign', 'Patanjali'],
    reactions: { truth: 223, insight: 178, dharmic: 289 },
    comments: 38,
    shares: 62,
    bookmarks: 145,
    timestamp: '2024-04-01T15:30:00Z',
  },
];

export const TRENDING_POSTS: Post[] = [
  {
    id: 'tp1',
    authorId: 'u3',
    authorName: 'Vikram Patel',
    authorUsername: 'vikram.patel',
    authorAvatar: '',
    authorKarma: 967,
    type: 'text',
    title: 'The ₹100 Lakh Crore Opportunity: Bharat\'s Cultural Economy',
    content: 'McKinsey estimates India\'s creative economy at $250B by 2030. But we\'re barely scratching the surface of our true asset: 5,000 years of civilizational knowledge, art, music, dance, architecture, and philosophy. The Gurukul system produced polymaths. We need to rebuild it for the digital age. The opportunity is unlike anything the world has seen.',
    community: 'Dharmic Investors',
    communityId: 'c6',
    tags: ['Economy', 'Culture', 'Bharat', 'Opportunity', 'Investment'],
    reactions: { truth: 567, insight: 423, dharmic: 489 },
    comments: 134,
    shares: 289,
    bookmarks: 378,
    timestamp: '2024-04-03T08:00:00Z',
  },
  {
    id: 'tp2',
    authorId: 'u6',
    authorName: 'Meera Devi',
    authorUsername: 'meera.devi',
    authorAvatar: '',
    authorKarma: 856,
    type: 'image',
    title: '108 Sacred Geometries of Bharat — Thread',
    content: 'Each yantra in our tradition is a map of consciousness. The Sri Yantra — composed of nine interlocking triangles — encodes the dance of Shiva and Shakti, and simultaneously maps to perfect Fibonacci ratios. I\'ve spent 3 years digitizing and studying 108 sacred geometries from temple archives. Here\'s what I found.',
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format',
    community: 'Dharmic Artists',
    communityId: 'c7',
    tags: ['SacredGeometry', 'Yantra', 'Art', 'Mathematics', 'Spirituality'],
    reactions: { truth: 445, insight: 389, dharmic: 534 },
    comments: 98,
    shares: 212,
    bookmarks: 312,
    timestamp: '2024-04-02T12:00:00Z',
  },
  {
    id: 'tp3',
    authorId: 'u5',
    authorName: 'Rahul Gupta',
    authorUsername: 'rahul.gupta',
    authorAvatar: '',
    authorKarma: 734,
    type: 'text',
    title: 'Zero Carbon by 2047: A Dharmic Engineering Vision',
    content: 'India has a unique opportunity: we can leapfrog the fossil fuel era entirely. Our solar irradiance is 5-7 kWh/m² per day — among the highest globally. Combined with our metallurgical tradition (Wootz steel, rust-proof Delhi pillar), our engineering lineage, and 600 million youth, we have everything we need. The question is will.',
    community: 'Climate Scientists',
    communityId: 'c8',
    tags: ['Climate', 'Energy', 'India2047', 'Engineering', 'Solar'],
    reactions: { truth: 423, insight: 356, dharmic: 401 },
    comments: 112,
    shares: 198,
    bookmarks: 267,
    timestamp: '2024-04-01T10:00:00Z',
  },
  {
    id: 'tp4',
    authorId: 'u4',
    authorName: 'Ananya Krishnan',
    authorUsername: 'ananya.krishnan',
    authorAvatar: '',
    authorKarma: 1567,
    type: 'text',
    title: 'Why We Must Reclaim "Rishi" as a Profession',
    content: 'In ancient Bharat, Rishis were our greatest scientists. They worked on consciousness research, astronomy, linguistics, medicine, and mathematics — not as separate disciplines, but as one unified inquiry. Aryabhata, Brahmagupta, Sushruta, Charaka — these were people who combined deep spiritual practice with rigorous empirical investigation. We need this synthesis again.',
    community: 'IKS Enthusiasts',
    communityId: 'c1',
    tags: ['Rishi', 'Science', 'IKS', 'AncientWisdom', 'Research'],
    reactions: { truth: 512, insight: 434, dharmic: 378 },
    comments: 156,
    shares: 234,
    bookmarks: 289,
    timestamp: '2024-03-31T09:00:00Z',
  },
];
